nVendors/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import frontpage, about

urlpatterns = [
    path('about/', about, name='about'),
    path('admin/', admin.site.urls),
    path('', include('userprofile.urls')),
    path('', include('store.urls')),
    path('', frontpage, name='frontpage'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('search/', views.search, name='search'),
    path('add-to-cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('change-quantity/<str:product_id>/', views.change_quantity, name='change_quantity'),
    path('remove-from-cart/<str:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/', views.cart_view, name='cart_view'),
    path('cart/checkout/', views.checkout, name='checkout'),
    path('cart/success/', views.success, name='success'),
    path('<slug:slug>/', views.category_detail, name='category_detail'),
    path('<slug:category_slug>/<slug:slug>/', views.product_detail, name='product_detail'),
]

store/models.py
from statistics import mode
from django.contrib.auth.models import User
from django.db import models
from django.core.files import File
from io import BytesIO
from PIL import Image

class Category(models.Model):
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)

    class Meta:
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.title

class Product(models.Model):
    DRAFT = 'draft'
    WAITING_APPROVAL = 'waitingapproval'
    ACTIVE = 'active'
    DELETED = 'deleted'

    STATUS_CHOICES = (
        (DRAFT, 'Draft'),
        (WAITING_APPROVAL, 'Waiting approval'),
        (ACTIVE, 'Active'),
        (DELETED, 'Deleted'),
    )

    user = models.ForeignKey(User, related_name='products', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    slug = models.SlugField(max_length=50)
    description = models.TextField(blank=True)
    price = models.IntegerField()
    image = models.ImageField(upload_to='uploads/product_images', blank=True, null=True)
    thumbnail = models.ImageField(upload_to='uploads/product_images/thumbnail', blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=ACTIVE)

    class Meta:
        ordering = ('-created_at',)
    
    def __str__(self):
        return self.title
    
    def get_display_price(self):
        return self.price / 100

    def get_thumbnail(self):
        if self.thumbnail:
            return self.thumbnail.url
        else:
            if self.image:
                self.thumbnail = self.make_thumbnail(self.image)
                self.save()

                return self.thumbnail.url
            else:
                return 'https://image-placeholder.com/images/actual-size/200x200.png'

    def make_thumbnail(self, image, size=(300, 300)):
        img = Image.open(image)
        img.convert('RGB')
        img.thumbnail(size)

        thumb_io = BytesIO()
        img.save(thumb_io, 'JPEG', quality=85)
        name = image.name.replace('uploads/product_images/', '')
        thumbnail = File(thumb_io, name=name)

        return thumbnail

class Order(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    zipcode = models.CharField(max_length=255)
    city = models.CharField(max_length=255)
    paid_amount = models.IntegerField(blank=True, null=True)
    is_paid = models.BooleanField(default=False)
    payment_intent = models.CharField(max_length=255)
    created_by = models.ForeignKey(User, related_name='orders', on_delete=models.SET_NULL, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='items', on_delete=models.CASCADE)
    price = models.IntegerField()
    quantity = models.IntegerField(default=1)
    
    def get_display_price(self):
        return self.price / 100

store/forms.py
from django import forms

from .models import Product, Order

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('first_name', 'last_name', 'address', 'zipcode', 'city',)

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ('category', 'title', 'description', 'price', 'image',)
        widgets = {
            'category': forms.Select(attrs={
                'class': 'w-full p-4 border border-gray-200'
            }),
            'title': forms.TextInput(attrs={
                'class': 'w-full p-4 border border-gray-200'
            }),
            'description': forms.Textarea(attrs={
                'class': 'w-full p-4 border border-gray-200'
            }),
            'price': forms.TextInput(attrs={
                'class': 'w-full p-4 border border-gray-200'
            }),
            'image': forms.FileInput(attrs={
                'class': 'w-full p-4 border border-gray-200'
            })
        }

store/views.py
import json
import stripe

from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect

from .cart import Cart
from .forms import OrderForm
from .models import Category, Product, Order, OrderItem


def add_to_cart(request, product_id):
    cart = Cart(request)
    cart.add(product_id)

    return redirect('cart_view')


def success(request):
    return render(request, 'store/success.html')


def change_quantity(request, product_id):
    action = request.GET.get('action', '')

    if action:
        quantity = 1

        if action == 'decrease':
            quantity = -1

        cart = Cart(request)
        cart.add(product_id, quantity, True)

    return redirect('cart_view')


def remove_from_cart(request, product_id):
    cart = Cart(request)
    cart.remove(product_id)

    return redirect('cart_view')


def cart_view(request):
    cart = Cart(request)

    return render(request, 'store/cart_view.html', {
        'cart': cart
    })


@login_required
def checkout(request):
    cart = Cart(request)

    if cart.get_total_cost() == 0:
        return redirect('cart_view')

    if request.method == 'POST':
        data = json.loads(request.body)
        first_name = data['first_name']
        last_name = data['last_name']
        address = data['address']
        zipcode = data['zipcode']
        city = data['city']

        if first_name and last_name and address and zipcode and city:
            form = OrderForm(request.POST)

            total_price = 0
            items = []

            for item in cart:
                product = item['product']
                total_price += product.price * int(item['quantity'])

                items.append({
                    'price_data': {
                        'currency': 'usd',
                        'product_data': {
                            'name': product.title,
                        },
                        'unit_amount': product.price
                    },
                    'quantity': item['quantity']
                })

            stripe.api_key = settings.STRIPE_SECRET_KEY
            session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                line_items=items,
                mode='payment',
                success_url=f'{settings.WEBSITE_URL}cart/success/',
                cancel_url=f'{settings.WEBSITE_URL}cart/',
            )
            payment_intent = session.payment_intent

            order = Order.objects.create(
                first_name=first_name,
                last_name=last_name,
                address=address,
                zipcode=zipcode,
                city=city,
                created_by=request.user,
                is_paid=True,
                payment_intent=payment_intent,
                paid_amount=total_price
            )

            for item in cart:
                product = item['product']
                quantity = int(item['quantity'])
                price = product.price * quantity

                item = OrderItem.objects.create(order=order, product=product, price=price, quantity=quantity)

            cart.clear()

            return JsonResponse({'session': session, 'order': payment_intent})
    else:
        form = OrderForm()

    return render(request, 'store/checkout.html', {
        'cart': cart,
        'form': form,
        'pub_key': settings.STRIPE_PUB_KEY,
    })


def search(request):
    query = request.GET.get('query', '')
    products = Product.objects.filter(status=Product.ACTIVE).filter(
        Q(title__icontains=query) | Q(description__icontains=query))

    return render(request, 'store/search.html', {
        'query': query,
        'products': products,
    })


def category_detail(request, slug):
    category = get_object_or_404(Category, slug=slug)
    products = category.products.filter(status=Product.ACTIVE)

    return render(request, 'store/category_detail.html', {
        'category': category,
        'products': products
    })


def product_detail(request, category_slug, slug):
    product = get_object_or_404(Product, slug=slug, status=Product.ACTIVE)

    return render(request, 'store/product_detail.html', {
        'product': product
    })

store/templates/store/cart_view.html
{% extends 'core/base.html' %}

{% block title %}Cart{% endblock %}

{% block content %}
    <div class="max-w-6xl mx-auto p-6 bg-white shadow-md rounded-lg">
        <h1 class="mb-6 text-2xl">Cart</h1>

        {% if cart|length %}
            {% for item in cart %}
                <div class="px-4 py-4 mb-2 bg-teal-100 rounded-lg flex items-center">
                    <div>
                        <img src="{{ item.product.get_thumbnail }}" class="w-20">
                    </div>

                    <div class="pl-6">
                        <h2 class="text-2xl font-bold">{{ item.product.title }}</h2>

                        <p class="text-lg text-black">${{ item.product.get_display_price }}</p>

                        <div class="mt-4 mb-4">
                            <a href="{% url 'change_quantity' item.product.id %}?action=increase" class="px-3 py-2 rounded-full bg-teal-500 text-white">+</a>
                            <span class="mx-2">{{ item.quantity }}</span>
                            <a href="{% url 'change_quantity' item.product.id %}?action=decrease" class="px-3.5 py-2 rounded-full bg-teal-500 text-white">-</a>
                        </div>

                        <a href="{% url 'remove_from_cart' item.product.id %}" class="inline-block">
                            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M14.74 9l-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 01-2.244 2.077H8.084a2.25 2.25 0 01-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 00-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 013.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 00-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 00-7.5 0" />
                            </svg>
                        </a>
                    </div>
                </div>
            {% endfor %}

            <hr class="mt-4 mb-4">

            <strong>Total cost: </strong>${{ cart.get_total_cost }}

            <hr class="mt-4 mb-4">

            <a href="{% url 'checkout' %}" class="inline-block px-3 py-2 bg-teal-500 rounded-xl text-white">Checkout</a>
        {% else %}
            <div class="px-6 py-6 bg-gray-300">
                You don't have any products in the cart yet...
            </div>
        {% endif %}
    </div>
{% endblock %}

store/templates/store/category_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ category.title }}{% endblock %}

{% block content %}
    <h1 class="text-2xl">{{ category.title }}</h1>

    {% include 'store/partials/products.html' %}
{% endblock %}

store/templates/store/checkout.html
{% extends 'core/base.html' %}

{% block title %}Checkout{% endblock %}

{% block content %}
    <h1 class="mb-6 text-2xl">Checkout</h1>

    <h2 class="text-xl text-gray-500">Total cost: ${{ cart.get_total_cost }}</h2>

    <form method="post" id="checkout-form">
        {% csrf_token %}
        <div>
            <label for="id_first_name" class="block text-gray-700">First Name</label>
            <input type="text" name="first_name" id="id_first_name" class="mt-2 block w-full py-4 px-6 bg-gray-100 rounded-xl">
        </div>

        <div>
            <label for="id_last_name" class="block text-gray-700">Last Name</label>
            <input type="text" name="last_name" id="id_last_name" class="mt-2 block w-full py-4 px-6 bg-gray-100 rounded-xl">
        </div>

        <div>
            <label for="id_address" class="block text-gray-700">Address</label>
            <input type="text" name="address" id="id_address" class="mt-2 block w-full py-4 px-6 bg-gray-100 rounded-xl">
        </div>

        <div>
            <label for="id_zipcode" class="block text-gray-700">Zipcode</label>
            <input type="text" name="zipcode" id="id_zipcode" class="mt-2 block w-full py-4 px-6 bg-gray-100 rounded-xl">
        </div>

        <div>
            <label for="id_city" class="block text-gray-700">City</label>
            <input type="text" name="city" id="id_city" class="mt-2 block w-full py-4 px-6 bg-gray-100 rounded-xl">
        </div>

        <div id="errors" class="hidden my-3 px-4 py-4 bg-red-200 rounded-xl"></div>

        <button class="py-2 px-3 rounded-xl mt-10 text-white bg-teal-500 hover:bg-teal-600" onclick="buy(event)">Checkout</button>
    </form>

{% endblock %}

{% block scripts %}
<script type="application/javascript" src="https://js.stripe.com/v3/"></script>
<script>
    function validate(first_name, last_name, address, zipcode, city) {
        let errors = [];

        if (first_name === '') {
            errors.push('The first name is missing');
        }

        if (last_name === '') {
            errors.push('The last name is missing');
        }

        if (address === '') {
            errors.push('The address is missing');
        }

        if (zipcode === '') {
            errors.push('The zipcode is missing');
        }

        if (city === '') {
            errors.push('The city is missing');
        }

        let html = '';

        for (let i = 0; i < errors.length; i++) {
            html += errors[i] + '<br>';
        }

        let errorsElement = document.getElementById('errors');

        if (errors.length) {
            errorsElement.classList.remove('hidden');
            errorsElement.innerHTML = html;

            return false;
        } else {
            errorsElement.classList.add('hidden');

            return true;
        }
    }

    function buy(event) {
        event.preventDefault();

        const first_name = document.getElementById('id_first_name').value;
        const last_name = document.getElementById('id_last_name').value;
        const address = document.getElementById('id_address').value;
        const zipcode = document.getElementById('id_zipcode').value;
        const city = document.getElementById('id_city').value;

        if (validate(first_name, last_name, address, zipcode, city)) {
            let data = {
                'first_name': first_name,
                'last_name': last_name,
                'address': address,
                'zipcode': zipcode,
                'city': city,
            }

            let stripe = Stripe('{{ pub_key }}');

            fetch('/cart/checkout/', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-CSRFToken': '{{ csrf_token }}'
                },
                credentials: 'same-origin',
                body: JSON.stringify(data)
            })
            .then(function(response) {
                return response.json()
            })
            .then(function(session) {
                return stripe.redirectToCheckout({ sessionId: session.session.id })
            })
            .then(function(result) {
                if (result.error) {
                    alert(result.error.message)
                }
            })
            .catch(function(error) {
                alert(error)
            });
        }

        return false;
    }
</script>
{% endblock %}

store/templates/store/product_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ product.title }}{% endblock %}
{% block meta %}
<meta name="description" content="{{ product.description }}">
<meta name="author" content="nVendors">
<meta property="og:title" content="nVendors | {{ product.title }}">
<meta property="og:description" content="{{ product.description }}">
<meta property="og:type" content="article">
<meta property="og:url" content="https://nvendors.com{% url 'product_detail' product.category.slug product.slug %}">
{% if product.image %}
<meta property="og:image" content="https://nvendors.com{{ product.image.url }}">
{% endif %}
{% endblock %}

{% block content %}
    <div class="flex mt-20">
        {% if product.image %}
        <div class="w-1/2">
            <img src="{{ product.image.url }}" alt="Image of {{ product.title }}" class="w-80 h-80 object-contain">
        </div>
        {% endif %}

        <div class="w-1/2 pl-4">
            <h1 class="text-4xl font-bold">{{ product.title }}</h1>

            {% if product.description %}
                <p class="mt-4">
                    {{ product.description|linebreaks}}
                </p>
            {% endif %}

            <p class="text-2xl text-black-500 mt-2">
                ${{ product.get_display_price }}
                - Vendor:
                <a href="{% url 'vendor_detail' product.user.id %}" class="text-2xl text-black">{% firstof product.user.get_full_name product.user.username %}</a>
            </p>

            <a href="{% url 'add_to_cart' product.id %}" class="inline-block px-4 py-2 bg-teal-500 rounded-xl text-white mt-4">Add to cart</a>
        </div>
    </div>
{% endblock %}

store/templates/store/search.html
{% extends 'core/base.html' %}

{% block title %}Search{% endblock %}

{% block content %}
    <h1 class="text-2xl">Search</h1>

    <h2 class="text-xs text-gray-600">Search results for "{{ query }}":</h2>

    {% if products %}
        {% include 'store/partials/products.html' %}
    {% else %}
        <p>There are no products matching!</p>
    {% endif %}
{% endblock %}

store/templates/store/success.html
{% extends 'core/base.html' %}

{% block title %}Success{% endblock %}

{% block content %}
    <h1 class="mb-6 text-2xl">Success</h1>

    <p>
        Thank you for shopping with us!
    </p>
{% endblock %}